//! synapse — LLM router and gateway.
pub mod ai_task_type;
pub mod config;
pub mod embeddings;
pub mod error;
pub mod gateway;
pub mod guard;
pub mod jev_hybrid;
pub mod jev_native;
pub mod ledger;
pub mod observability;
pub mod pricing;
pub mod providers;
pub mod resilience;
pub mod routing;
#[cfg(feature = "server")]
pub mod server;
pub mod vertex_endpoint;
pub mod vertex_native;
